name: pengcook

volumes:
  db:
  grafana:
  prom:

services:
  db:
    image: mysql:8.0.38
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: pengcook
      MYSQL_ROOT_PASSWORD: root
      LANG: C.UTF-8
      TZ: Asia/Seoul
    volumes:
      - db:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    configs:
      - source: grafana-config
        target: /etc/grafana/provisioning/datasources/ds.yaml

  loki:
    image: grafana/loki
    restart: unless-stopped
    ports:
      - 3100:3100

  prom:
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - prom:/prometheus
    configs:
      - source: prom-config
        target: /prometheus/prometheus.yml

  node:
    image: prom/node-exporter
    restart: unless-stopped
    ports:
      - 9100:9100
    pid: host
    command:
      - "--path.rootfs=/host"
    volumes:
      - "/:/host:ro"

configs:
  grafana-config:
    content: |
      apiVersion: 1
      datasources:
      - name: Loki
        type: loki
        access: proxy
        orgId: 1
        url: http://loki:3100
        basicAuth: false
        isDefault: true
        version: 1
        editable: false

      - name: Prometheus
        type: prometheus
        access: proxy
        orgId: 1
        url: http://prom:9090
        basicAuth: false
        isDefault: false
        editable: false
  prom-config:
    content: |
      scrape_configs:
        - job_name: 'pengcook'
          metrics_path: '/actuator/prometheus'
          scrape_interval: 15s
          static_configs:
            - targets: ['host.docker.internal:8080']
      
        - job_name: 'node'
          scrape_interval: 15s
          static_configs:
            - targets: ['node:9100']
