spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(cn6onsNXSnrnvANMmBDbQSB6OP/o03OBqiJ/pNSOQcMqMEBjJ/Z9O2XwRHz91Mwby+b/6BE/dgWVwdNyj+mtQMkuBfp/gLsTbsTx59qPfOw5XWZfCFadailfuzzMYXeWFrz/myWwyXFAB9BodfQinJD8t4M0d3SnfP1an6fzrp4=)
    username: ENC(DlL3wN5qVKsCmYegk8VBzuI14OT3CkqeYA5Cg7NPObiTUeM+1oJsGKEWkUdnRcMf)
    password: ENC(Xljdaq5zSKNLXbvnubUmz/nwBDWvx9P0AOj6Co1OiywEbasCulkNi98VI4uapwYA)

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

jwt:
  secret: ENC(D+LidASEUNdtQfNTJ5u/1KEFLFgsfWdLtG1ED4+pIdAbZX1xdQSlkIpJT2S+9LmGTjgZiOZZfLSu8dcj18dWMzudDfob28iSGOZdpPexoqeE5ZxbQgsUDm/AEaEAGJ1AwVmZWWo8sfvg2sidGk/aOd6yr1krrnSOfr088kd8MCpuhu5my/fT5CfgboBB/feJoC+rbM15apC+qGKP8ju+pE1zE/iwvuJwd0bHHWqs0FA=)

firebase:
  service-account: ENC(ejQ2P9DbJpROBH7AAO/7BsqHdEaQ4tWIyhl1LvJl6C6Pg9tVLSNq/4TxpTUbbDD5tm4kVOxqa8lqG5JhqMG0YUrxK9W4qomy76vjf6ZjZOuE11+TqWMB3jo75xAQvQWy08FY4W06JRnSy3HXIpFsFTouHfaQOFpwpNi5qL6mtwiUU4Hup797+Vmk0rZHK3hAXT9Br05fobQEq/yeKCYQ1K0V3yKfKwFwOHlHPvdmj/Ntz7UfSHWjAil3GWlYPa4RKreYxmNguDb68X+Ol2itjTU3o7muh54yKoools5EGpqmT8IHbiIuOSHMQkbMmKxEHNYfY0sBuwfuop/gbJZmP6VlumtyDZcDsbvyBW9XR6Tq5T+21R+VW3zWgHFpL/nAf5Vnh84uSAexahbYCj7LLMTiTsjgRVemBRgdp/L5sB2KZPUG9GPVseLR1JkvndGeqqffGXnD13DSsVoIlbXMkCNyaeZPsVR1Bg2K5mU/3VCEEZjrpY9k0daUsePDj4Fk5rl5krH/wAMLegx1FyRhtc3su2A+VUV4+HZfCZx6DhmP3+Ua3VKc/cD4wGGdgdl9v4rIK3rQluf6Os+lHGLarQ1ZL4CNFMbjNkw/RYTAjKwpysy9LyabypP3f0TN/6uXfM/57ILxA4KDNgkG6EWpD4Ww+7zu/YuDHKjiwT83Rz5qLewX+q9e4d59xBuKzTFt7wpIcNwvw2tOF2CrcEDG4Z3/ky43p6m//rWbw5ezDZUcvWQwl9ITfACfZXuusuNslaMVGQ/m+iXZajvetNzXAWSpK3lQNk+6KMxKfk7G1kuO5DlK9CZKrxGYOOoW7DVwWHk3ZRL5JrW+OnswFhorKXKz0/UrnSNgxgCGfduaShUINC3FjEvyHXBb7IkNegyJ2oP1/SrV/smkecVxq8gwMxuJ07zm0Doiqn/tuZdp1efImNgp3u29gx6cPk6n2IV3j7Nv+XXrqFaOkxtFWSAyEtjrVwQLG5O/aX9m7Qjv3hEYARUzG0K848RBWVwntBebStypucvCsuanvgaD73DkU9EzUaqQz9f83dyS5hUT5tQ2n98giKkZ3xc5gNQyMNvtDxWZXPIbSFm6GIneOESWHTk9PZu3AJVpBmy2R8qzwFbeO1XRTMOlWjbbJGmWDK53Z7UZhcly/tBTx4o4d2t7n1y1d5gu2VLXlCZfX+v++6w3xuxf3/qXmd8cNMU9ihfrvagNByTxOmZ517MKBInyu12igDx8odB/fS5bLpmWC0hUWnyujRd+dlk+5A/Seyn5yKiv42AT4KCyvyyKmbhgozz0J7d4t5O47rqQvZjOVjbbV0Jh1XyQQR/1wOGMRyVdSRPFGaY3WUYeFqY9fxKAyGC6YZbhACLUUnOHMLP5szuFuC4vgknt1lZsUSkGBqSEz9AYShbb02Kc9rzrUf6VcIulYzoM1Y2VFuzorrlMtxhURmtDj4OR3xvQxJWKWM6xI37/e2fohk64JfwUloGnM8sFCLmko6CQM/DLuuE/6vpW6UJ6Rwz8i9ptdxApDcOa0ODsONoTbbnsVHMfBR0u6sxXR593i/14Vrsu8W7VJaGcYAweRb1hGMKDaKC4lMyvHWec69pGZNNXblMQ7m99cY2UXcOmEnNsuQf7kSJCXhbdM6bFx+rWOTRu4HbDNhSCn/Oq4v1bXBvK/Es1CZwcLpCP0LorToedUn+BpQHXhrphk1ltBzpjIybL1jF0NDkylaP9aC6WsTlVXcjyVqjtkdWAOL2xjp+1oGTOXlWVwaW2ldnOgH56LApPAarexpy/Pmmx+SoZDc2k4dNNADD21NqW64VR3LRToJmq6z9XsntgKY7z1JweyRCMPbJQ2oEiPc6+7gxPftWtgYCUA/FUO4jylMmCg6dsOZC0+7FMOl3kbeJYxYs6S9QWjgYK1O5iePjE6GFf7zBO/6Gq9tjrbUKcyedMozHbI7YxgNE9nuMgNJb3Um01aSswaXrYdrhxTiAtPWrWrlaUnKOar0NnxPLP6/345MJ8fMtPte078D5C9OqMz6mzIa42x9QQEooH/1UXNwHBYWumgJ+Hw2Og1AECUjIursq0zW6uyVm/nW9b0t9CQsHeKsUFDUpkSgcgUzrsZlX4Tp8bX6QMhQYMspanjiTRT3TL5x8YHMrlZf6rRPL1eIQcX/guGNP5h6vYeJWyw1b2yDQf5zfR3+C+uP1aPHi6yFf0O8t202z1A8wUyizcgD2WvwjgqS/MUBz1bnIZgu1EvpQuJKYRLcobZ2bVXDranLZrBGjQs4d5x/dHECUPEGfNWgBYWrDZ3wiJHWcp6J98kNkZkHT1uQa4Bt6I3p7U/USErCQiHJP3Iq1DlC/Q+MkRt9KuHqm1WMIngNcIde1Ef6233m8g5VOrJ0Cvx2BV9+gyn86c3XMORPPkd+MwGhIsHctUIlOtCC6H5IRAilqfUEQDRPIRUr/1IKQD7vT5bkDNChUtlcyM5ja+MN+QcNeHItuJOKud8FomUepSxgG8inN1bI0Q76XvscF6lhKc5lSvtRFs4qdQSxqDnnijAeuaadw/0XPlVnKYD1RScoAYYohKy+rf6UddcUYhaB3dYsso/rsiqUwjllihwSejLbahliJjGQVFFnygrn+eRmQoseByvY8YP+gDnchXNCdzhcRJY4Ju3actBjHh7TR20cAcSJHDu3ffQJbWCFdBmiAWSRaWkNsGbj0IEa6/dEUacAJpL0ejHWweoSvK1yt5/XVdg9pm6BBMiS4WMGx0NUYXhWQsDVJ5Cdihzh6iu+n0r+o6AejNqbcucJqdrOHtqaFH8AipzdJxVlZwIsKnCnRHznyKHChdYnP7d2pBtNQ1ORZGpne5b4Akz1UR+MhfCQGP5jT/M6neWzHLUrD+Ejx9GURP1l7hzdoockmJ8U6U4evs0UFlRO1eaTDrwAFdG53VUYyOWIoQI7Uox3aRSw7i9ZAusbNZ3J2I1zr+nMcXn/AxaILSRZAIwHf8kGHnV3KsrTjxJXdDNP0wZwStYJdTPh905tKk5q/7293Zml6O6bOtzxIYPJvh41CuolBxMMQUb7Fm2O3dmJmXF7tPdcVTkOdCVYOCTu68iZxnfD/XAWVie10l0Ic4ETidnkdojqLz4nL9U7SO94yaEXAyDp1wSzTJAEtHpDRRAJZtQECt6BodM6gECd2FcwyKG9seBa2VDHjgYj1C/TvWkwsuyd0f0LyT/BFFDDFFANcF0MO/dQ0oUHCLl5h2zLY=)
  project-name: ENC(Bx4psOQ3Jx2o13s96GCxyiQxzpFFFZwacbt6blpeja8ff/Vzru0jQTIs4EcZNEd+)

cloud:
  aws:
    S3:
      bucket: ENC(rKxRm4yCCuPIbYo59E7ImxNwsSHbrIubVtNyEe6EPbPFM+Bu16dnqPorXLPD18S57aSsrajMY8tYc3XKw7Gwug==)
      path: ENC(ZMKZRrEXXpiAXq6C/RkvuRX29u8h58J7ZAuA/Xb+NkQ+Ae/Ix1NpErVRcYaYv0cz)
      s3-url: ENC(O/OI16EMUuXwRIbCifs4WXz4fZFTskquGw4Xg5iKa6/pxz0GbmSrnlqYceinry1y15TEU78j8pmwfJYBZXZlpTTnp1bMpmIqe5fsVjfpX2bZljGTwElJLYY6XEvhnaJe)
      cloudfront-cname: ENC(eG3jV3fA2iMks/OfVdEoOC1yuP00D/sTquppxx27pJl6YdMcNfFcX1PUwingvuNsNzoUdGO3Oie+upv/OFGcCA==)
    region:
      static: ENC(QHjkS/cQk6BtfKT6UkdHZrnxZKGCvSsc15GvFz/KKBf25F5XBWhLAjEtHjk+up3V)

management:
  endpoints:
    web:
      exposure:
        include: prometheus

logging:
  level:
    org:
      zalando:
        logbook:
          Logbook: TRACE

logbook:
  predicate:
    exclude:
      - path: /actuator/**
