spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:pengcook
    username: sa
    password:

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
