spring:
  jpa:
    hibernate:
      ddl-auto: validate

jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}

jwt:
  access-token:
    expire-in-millis: 86400000
  refresh-token:
    expire-in-millis: 2419200000

springdoc:
  enable-default-api-docs: false
  api-docs:
    path: /openapi3.yaml
