spring:
  jpa:
    hibernate:
      ddl-auto: validate

jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}

jwt:
  access-token:
    expire-in-days: 1d
  refresh-token:
    expire-in-days: 30d

springdoc:
  enable-default-api-docs: false
  api-docs:
    path: /openapi3.yaml

logging:
  level:
    org:
      zalando:
        logbook:
          Logbook: TRACE
