spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pengcook?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

jwt:
  secret: ENC(PMp06UdOJEXk9e7bpjHZunoeLhFdeTqCRRrn/WZ2xBnGvd9+eIAe2TCCRBgBEH9pGwfDCIhnZeHeEs4ownlWCeGOKEhrl5wpMkJX8ycus7kqlR6XYREK8rDGDH2jPwQtda97ZQ6Mk6nJ00x9Sx6tZts4z0OnbRkgPDCPhQV6M3TJpdJHFeYmYq6b+5wGVcnBA/9CVm1FGa/d0LPbtg2fAJ/mVpIer0VhTl/hUmUvjPI=)
  expire-in-millis: 86400000
