spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(MDL1AcKr9jd9NRO0JRWgHNDzVTUDZMZSPrhv/F8Zgr9+fnvvd53pALeR8UrcLhDyB4Tw8PDLZZc1+uR2WWIt2m7dB1zk6/xUlEBz7WTi+98WosqWWIwC/80iqnWVlNHFlZoqky5c2PEp1qxHl9pAUQ==)
    username: ENC(M4z9d3ZA9vsM6dszL8Irp4CYS8QPZagRCFt/aDcKd/JzPLp3cm4os0N4Q1UsoTEf)
    password: ENC(XgbKU4yM/P3edIbLl9SysxhawJySVlO5f2BBihSvS0l9wSxywr3lPpApgFIEjCEu)

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

jwt:
  secret: ENC(+tXNIDNrGAWDx/vMv+AO5KkhPG5iY/mkjagusXWcO16RVHEBI9rq40GukA/RU6X7mEcBPYgWHhlmA5ql6XQU349AIhsJ6Hd3g9f4FD4zcvkHDmJtRV8CAvr9XaMQbtSvCRWMoipYKbTFs5SobwGO1xWntcFIX8LCWxM0wi58Hzz4eJvo7naZiSg3Hqp39zH0pAR8LRP5qbhfyFKH7pIX6AB7q2SqYJIre3T7JIeU5U4=)

firebase:
  service-account: ENC(9nDZ4unkSEmUv0wfHX9nYsBvDVXKLdtC/EJvLKg5pkzdytwET85+MzTJISykuYEbAp6aQwzlFfDnIQztfpnMq/v2a0mzn2EZC14qCy5RbKeosZ9Zn0K3+Pk+PosAD13p5LE1jxFLqqPpshvflw74oPESo2x/ppl7jOYZfKEaaUks2CLWcpm3t7PGEqpuRLKDGLsel1nMWgSCj8IBxB2vq7NAjSJV3AGwSktDmp5bxJSN5pXBa49YxJRb+ZApR/nYC6B+uu1T4zAfWMnSrPI/VA6XyqE/RxYyQRs+sWPVSIoDkjJw4iEx3kCT6WlAcUZ1FJnVGsaKqA4iVpUtKR2fA7LZOo+Epb15XzFjp0WzKgSW7YsiHWoLtNV6euGWI+ZcL8NzbbEfqkrHiGz9SnXE006JurB9MduN6/lPhfwFpZju0q0231WEvvIh8G2bQXzMDw+lZc2KwPTWAhir9ZqznCDagwx9y9pH5n9xCmbB8iuVOBocfhDsMPzuAytsaJy647Ge1zXH0xrmxu+uiTHI+5KY2oam53s00Cgmln/Q+O/8/qJ3/i3IAR6XhY8CcMysdpq0ihSn4RjI92BtVQv1MxW6RzBFQdZyGbhe9a6EfNLGsaAWNT6tggg4oxEhIQy9IW2hiwK8toRWbA1ZeHB82rWaJHT3ZhljyhCDPUyUwsONfPShy2xHz2+F1g9nVUFxb8UGIJeFFziXhdx2HTXnELm1ZNK0X0hZ5GUTs3rTSBuZdBboGmYpR23JZ4wem39dE8Rje+x8aQmiQFFhlVMx3jM0MSx1/QcpnJ7gKsHKj/c0uvGQPUokJKzxxDjWPKDl59noz2SxwHMiRPm+muhSaB6t8Z4JMUvN/5qdGWnmZ4HdQa+SEFiHblSFtBFRz0/FxVeI9+9Nl6KlL2NZ5dO2qXDfPKCtwjUFuz5nYc4btxVBS/x+akc3U88nAvud1j3e4PLR+3cYP9khkbGq67LUH0ulCQkvhR74PEYiiCuUhHWBsEavbNWjyTVyUk7lBBuzl8COyQqy55RAl9sfLGDNVFhBG1a8XdKEZ6HalY0TZL7+KuEk+8yWqvFiYzgWgT5Y7I33QfF7BG9oN9kOBavGbeCfvko8tdiGNMeiA/uzZQBUa5vZuJTz34WW4Sjj8JSJygY/gapYVeDmW39QZanfxoF1TWIbR4Pt/OSJhwOQvxxGIXpY9FgCrMVPfvEatCse26L1IiunNFRCq43/DL7s6pHeP6zDnA21Q5+YHhPlxkVQ5MCui42h/37zvLky906JHEFwYBJt9s9hMCgP9o+ayDTTDFu/XjltmbwYKlI0FSIWELIwaq5NUm+XkfW+gT8Fdj96B5KOBCHS82jXZLI1WlHoq9JWnGg3amX0TSwVRHovml1kxuX9nmGAokF9jYaO5T/RVGEsD12gwFPmPCq7whDLdjavUnRltV72QlVhWG9UaN1XvT/fpUpSAfh587qCWtvhTpyB0ImwxGK9HUzVEk26P9lWfk8GfZNChYb8bdcQ+uyLLn8gbWas6jukcGrAWTY89d795nc9CRA9qCm3P2y0IKj86PbXZ9YRv+FixNXf3vD8Epq+QXYTCqc83JQNeSy5MT3gMFrobTsTAqL8iKYL5Oq5p8fcTg33YIT5WxnfWtuiBtz/RICbdyZNsgUCNcgOOLYzY0hFvc/ozLAawbHVoMioi4/TCmE1c1Z4PydEy5vc33w4yzfstl8C7M6p8k9dUZsa5KDGSftFyzuWqAhvTvix8jQXMYzdDJtzfYF1dHOjqQoD3ddpAtIqEBDNbAxTRIsS2JWx7/knP4fER3ulB1rd+wKRRuF6fVQ7a8dmc/GqLxlkfoAS9/PywdgvmOuzNf+8LMlfXfJgDyEWiA2Sz/rTg6rvVW2AjfziDBORZiXGi/KOjR+Qv1rrKIil4C6FvM4fA9ZeyLKsBKUyU2Hm6nY2cYyxcI2m3ltVSQjIG1ZK7K68jtrkWzkAAWRJMEwIyOrrnJuxFRHDXHh0Ycyic/nahJAnn6Tcu82erVuVguNQqIQA0V7zc/tEczEsjkeZ7zUNsTlwWIV9LvvWVT/8sFdfVVG13gy+/HFTaS8LgMqTHypr2yTmI3gnIPNd9PCGssr0zi3TIqn7zIj/pUHbqJic72/x7To36dk5xrzFtXbFy39JbIPuLoyB8ilqRpG3TLJ1/rdFxYhL5cWDnSQHDaZI+eyGCYnGdmBtS9pwbvAk8rFCT75+717BmAoH1amdhShY8ULH2ldeoX19Njmfo8NrZcWLBKu7hTsyfG4YbEyzytrqR7sybEA23jB4b+nT/AS4AvibcHZ2dC1+wA8kuq3WEAcKe9eKvDlUIBzFJ7UFbkq+T7YbWtlgMUNd0ZrALGmHwWUMK72KLfW7zmEKQJH7oM5a2kI0TeFkkkooz6xL34eO9KecOE/PRb0OsEX75UX9/nja+Wz+YI4eFuWUVeJoxMDvSrzaIabdauK2s4FL2GN9S8PN2M6+lMnE6HRyldNomMGy5+DWnclnjy0rpyNQ865CvXn1fuVSof4/IlUvqwRDfda+/WMFIajDDd8t7Vgx60NMHAejohn6272Kel5aJ6BOdAw6H4rrlqYBklotT/ON2XRTuRHl6IYZVle9Zj3y2reXGdtGeDVrlen3DRXR5dDbefVnEpFSzrO0c565DhYKnB/F0XjoJbcxyV3NICME5i6foSOMuKL3pyP5Yjjr3ML5r+JaefS9uJ7pTXGjzj+BTLsfroOLs+mN3HHVG+zDTswBMyPLfDD+qkB13Ru8fVmIfBGrB1R+yU+l51GJZT6Jm3hx1+pWnpy/iRHsrIMIurbzkKHWnzWFqb21Pc7BA3ntjprasmUuv+a2xn58pgdDWzDBo/Ho0PYbfJHdQYHdKLIxgQ6IuT30a2FRNRCRZu/HkKFX6PNUjef17H64FLk0BLGnsBf8SacrgpZx2Cy8w/xK6UfQ3NnuinNUsxu9d/FTgt67sCC2Ezte7NJJzB3Buh7eE8Xc6AASp2c1H9QaJCSMoO36u8Btrio/NXWok0EbuGVpaiPSO0M4KJzcOrYKdWXuyhLj9yNHxdu1bbSlh4UwrW4hodHv5Qi/LIirgKqqquggfNpEBDcSI1zEKWd5KdjjcZyMSlrJgI1iaTCUBYqhzccmIxEa+oOC8b3QgMrcWgVfZxr/uyW5vu9RJqUwxbc0ve3Ms9c1QVSsXdThjK1a467GKbwmdyb40bw0jICmapTXYv0+XteZZU7K/vwqEt0kh+oHRMKyLAyobOsgZwtno6B/HhB9+SkHlrO2bQZnAVXzghGw/b+x7o0XcHijYWj2RRtMVRHm)
  project-name: ENC(xdfH+UHlUvqfsfYLJqN1ZiBPPLh/xZflhx6sWYuZVy59c6MjjwryKy+6yRkNRoNr)

cloud:
  aws:
    S3:
      bucket: ENC(vHtLR4hquZmrp7cqlrr6vXrazA0rLJApEalSU6QPYX4O1GHrbQd9dquGAWtCy1vZcOVfFUZ5aDqqSMSrycfhlw==)
      path: ENC(enM1r+Mv5m9E/UFDfKiPN5mdu/JJ3BOvWgSW05+vDE4SaI4iHlnEN4vqZVa3pGxL)
      s3-url: ENC(vXFQrV7EqIN++so+O8z8ZrhzS9tqn0n2cxy1HeNfSYBqV6zNZm3BwKeRt+OlctQVHbBMUfXdCYdEcoxsgKtJnu8veV21IEe04+yEfQSe/u/44Gij3ekxVKRx6FZT+A4c)
      cloudfront-cname: ENC(74un+Yr6O9u4VwCyLGWBTLMU862azaovIEJP8+3ouJ2jxk+zTNDD6OFQLjzeBqK/vINfMT8DDt5AbOb18wAiAg==)
    region:
      static: ENC(a7sCLLXDx5Fn76E+NLdyxLoL3MEp6x1J/OcoFyg0ejxLrGAQ/O+82ZoDr6LXcRAt)

management:
  endpoints:
    web:
      exposure:
        include: prometheus

logging:
  level:
    org:
      zalando:
        logbook:
          Logbook: TRACE
logbook:
  predicate:
    exclude:
      - path: /actuator/**
      - path: /swagger-ui/**
      - path: /openapi3.yaml/**
