spring:
  jpa:
    open-in-view: false

jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}

jwt:
  access-token:
    expire-in-days: 1d
  refresh-token:
    expire-in-days: 30d

springdoc:
  enable-default-api-docs: false
  api-docs:
    path: /openapi3.yaml

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus

server:
  shutdown: graceful
