volumes:
  db:

services:
  db:
    image: mysql:8.0.38
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: pengcook
      MYSQL_ROOT_PASSWORD: root
      LANG: C.UTF-8
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
