volumes:
  db:
  prometheus:

services:
  db:
    image: mysql:8.0.38
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      LANG: C.UTF-8
    volumes:
      - db:/var/lib/mysql
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci

  app:
    image: pengcook/pengcook:dev
    restart: unless-stopped
    environment:
      JASYPT_PASSWORD: ${JASYPT_PASSWORD}
    ports:
      - 8080:8080
    links:
      - db
      - loki

  loki:
    image: grafana/loki
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    volumes:
      - prometheus:/prometheus
    entrypoint:
      - sh
      - -euc
      - |
        cat <<EOF > /prometheus/prometheus.yml
        scrape_configs:
          - job_name: 'pengcook'
            metrics_path: '/actuator/prometheus'
            scrape_interval: 15s
            static_configs:
              - targets: ['app:8080']
        EOF
        /bin/prometheus
    links:
      - app

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false

        - name: Prometheus
          type: prometheus
          access: proxy
          orgId: 1
          url: http://prometheus:9090
          basicAuth: false
          isDefault: false
          editable: false
        EOF
        /run.sh
    ports:
      - 3000:3000
    links:
      - loki
      - prometheus
