volumes:
  db:

services:
  db:
    image: mysql:8.0.38
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      LANG: C.UTF-8
    volumes:
      - db:/var/lib/mysql
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci

  app:
    image: pengcook/pengcook:dev
    restart: unless-stopped
    environment:
      JASYPT_PASSWORD: ${JASYPT_PASSWORD}
    ports:
      - 8080:8080
    links:
      - db
      - loki

  loki:
    image: grafana/loki
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana
    ports:
      - 3000:3000
    links:
      - loki
