volumes:
  grafana:
  prom:

services:
  loki:
    image: grafana/loki
    restart: unless-stopped
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml

  prom:
    image: prom/prometheus
    restart: unless-stopped
    volumes:
      - prom:/prometheus
    links:
      - app
      - node
    entrypoint:
      - sh
      - -euc
      - |
        cat <<EOF > /prometheus/prometheus.yml
        scrape_configs:
          - job_name: 'pengcook'
            metrics_path: '/actuator/prometheus'
            scrape_interval: 15s
            static_configs:
              - targets: ['10.0.0.187/prom']
        
          - job_name: 'node'
            scrape_interval: 15s
            static_configs:
              - targets: ['10.0.0.187/node']
        EOF
        /bin/prometheus

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    volumes:
      - grafana:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=https://mon.pengcook.net
    ports:
      - 3000:3000
    links:
      - loki
      - prom
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false

        - name: Prometheus
          type: prometheus
          access: proxy
          orgId: 1
          url: http://prom:9090
          basicAuth: false
          isDefault: false
          editable: false
        EOF
        /run.sh
