volumes:
  db:

services:
  db:
    image: mysql:8.0.38
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      LANG: C.UTF-8
    volumes:
      - db:/var/lib/mysql
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci

  app:
    image: pengcook/pengcook:dev
    restart: unless-stopped
    environment:
      PROFILE: ${PROFILE}
      JASYPT_PASSWORD: ${JASYPT_PASSWORD}
    ports:
      - 7848:8080
    links:
      - db