name: Android CI
on:
  push:
    branches:
      - an/feature/**
      - an/fix/**
      - an/ci/**
      - an/cd/**
      - an/refactor/**
      - an/build/**
      - an/perf/**
      - an/chore/**
  pull_request:
    branches:
      - main
jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build and test
        run: ./gradlew build test
        working-directory: ./android
