name: Backend CI

on:
  pull_request:
    branches:
      - be/dev

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    permissions:
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Generate test report
        working-directory: ./backend
        env:
          JASYPT_PASSWORD: ${{ secrets.JASYPT_PASSWORD }}
        run: |
          chmod +x ./gradlew
          ./gradlew jacocoTestReport

      - name: Add comment to PR with test coverage
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: ${{ github.workspace }}/**/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 0
          min-coverage-changed-files: 0
          update-comment: true
