name: Android Build CI Pipeline

on:
  push:
    branches:
      - main
      - an/**
  pull_request:
    branches:
      - main

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Create google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo "$GOOGLE_SERVICES_JSON" > ./app/google-services.json
      - name: Set up environment variable for BuildConfig
        env:
          BUILD_CONFIG_STRING: ${{ secrets.GOOGLE_WEB_CLIENT_ID }}
        run: |
          echo "BUILD_CONFIG_STRING=$BUILD_CONFIG_STRING" >> $GITHUB_ENV
      - name: Build and test
        run: ./gradlew build test
        working-directory: ./android
      - name: Use BuildConfig string in a script
        run: |
          echo "The BuildConfig string is: $GOOGLE_WEB_CLIENT_ID"
        env:
          BUILD_CONFIG_STRING: ${{ secrets.GOOGLE_WEB_CLIENT_ID }}
