name: Android Build CI Pipeline

on:
  push:
    branches:
      - main
      - an/prod/**
      - an/dev/**
      - an/feat/**
      - an/ci/**
      - an/release/**
  pull_request:
    branches:
      - main

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build and test
        run: ./gradlew build test
        working-directory: ./android
