name: Android Test CI Pipeline

on:
  push:
    branches:
      - main
      - an/**
  pull_request:
    branches:
      - main

jobs:
  clean_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Clean project
        run: ./gradlew clean
        working-directory: ./android
