name: Android Build CI Pipeline

on:
  push:
    branches:
      - main
      - an/**
  pull_request:
    branches:
      - main

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Create google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo $GOOGLE_SERVICES_JSON > ./android/app/google-services.json
      - name: Set up environment variable for BuildConfig
        env:
          GOOGLE_WEB_CLIENT_ID: ${{ secrets.GOOGLE_WEB_CLIENT_ID }}
        run: |
          echo google_web_client_id=\"$GOOGLE_WEB_CLIENT_ID\" > ./android/local.properties
      - name: Build and test
        run: ./gradlew build test
        working-directory: ./android
